 filebrowser:
        image: filebrowser/filebrowser
        container_name: filebrowser
        restart: unless-stopped
        labels:
          - "traefik.http.routers.covidstat.rule=Host(`abdikogluailesi.site`)"
          - "traefik.http.routers.covidstat.middlewares=covidstat-ssl"

          - "traefik.http.middlewares.covidstat-ssl.redirectscheme.scheme=https"
          - "traefik.http.middlewares.covidstat-ssl.redirectscheme.permanent=true"

          - "traefik.http.routers.covidstat-ssl.rule=Host(`abdikogluailesi.site`)"
          - "traefik.http.routers.covidstat-ssl.tls=true"
          - "traefik.http.routers.covidstat-ssl.tls.certresolver=letsEncrypt"
          - "traefik.http.routers.covidstat-ssl.tls.domains[0].main=abdikogluailesi.site"
